# Generated by Django 3.0.3 on 2020-03-21 06:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pastors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('verse', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('audio_size', models.IntegerField()),
                ('video_size', models.IntegerField()),
                ('video_1', models.FileField(blank=True, upload_to='videos/%Y/%m/%d/')),
                ('audio_1', models.FileField(blank=True, upload_to='audios/%Y/%m/%d/')),
                ('textfile_1', models.FileField(blank=True, upload_to='textfiles/%Y/%m/%d/')),
                ('photo_main', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('pastor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pastors.pastor')),
            ],
        ),
    ]
